baseURL = 'https://progresslog.me/'
languageCode = 'en-us'
title = 'Progress Log'
theme = "PaperMod"
relativeURLs = true


# Enable emoji support
enableEmoji = true
# Enable robots.txt
enableRobotsTXT = true
# Build drafts for local development
buildDrafts = false
# Build future content
buildFuture = false
# Build expired content
buildExpired = false


[params]
    googleAnalytics = "G-45YT1P594V"
    # Show read time
    ShowReadingTime = true
    # Show share buttons
    # ShowShareButtons = true
    # Show post navigation
    ShowPostNavLinks = true
    # Show breadcrumbs
    ShowBreadCrumbs = true
    # Show code copy buttons
    ShowCodeCopyButtons = true
    # Show word count
    ShowWordCount = true
    # Show tags
     ShowToc = true
    # Use Hugo's syntax highlighting
    useHugoToc = true
    
    # Cover image settings
    # images = ["/images/alien-red-planet-scenery-desktop-wallpaper.jpg"]

    # Comments (optional)
    # disqusShortname = "yourdisqusshortname"

# Profile Mode configuration
[params.profileMode]
    enabled = true
    title = "Damodar Patil"
    subtitle = """Daily blogs from my cybersecurity study journey  
Writing as I learn, share, and grow"""
    imageUrl = "/images/profile-picture.jpg"
    imageWidth = 140
    imageHeight = 140
    imageTitle = "Profile picture"

# Social icons for profile
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/DamodarPatil"

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/damodarpatil/"

[[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/damodar_83"

# Search configuration
[params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 2
    limit = 10
    keys = ["title", "permalink", "summary", "content", "tags"]

# Custom assets
[params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"

# Menu configuration
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 10
    
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 20
        
    [[menu.main]]
        identifier = "search"
        name = "Search"
        url = "/search/"
        weight = 25
        
    [[menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about/"
        weight = 30

[pagination]
  disableAliases = false
  pagerSize = 2
  path = "/posts/"

# Markup configuration
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNos = true
        style = "github-dark"

# Output formats (enables search)
[outputs]
    home = ["HTML", "RSS", "JSON"]